import { useState, type FormEvent, type ReactNode } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { useAuth } from '../auth/AuthProvider';
import Loading from '../components/Loading';
import type { FieldToCollect, IntakeConfig } from '../types';

// Default info the assistant collects. A full field editor comes in Step 5.
const DEFAULT_FIELDS: FieldToCollect[] = [
  { key: 'full_name', label: 'Full name', required: true },
  { key: 'phone', label: 'Phone', required: true },
  { key: 'reason', label: 'Reason for the visit', required: true },
];

export default function Onboarding() {
  const { session, profile, loading, refreshProfile } = useAuth();
  const navigate = useNavigate();

  const [businessName, setBusinessName] = useState('');
  const [profession, setProfession] = useState('');
  const [assistantName, setAssistantName] = useState('');
  const [welcome, setWelcome] = useState('');
  const [instructions, setInstructions] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  if (loading) return <Loading />;
  if (!session) return <Navigate to="/login" replace />;
  if (profile) return <Navigate to="/dashboard" replace />;

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    if (!session) return;
    setError(null);
    setSaving(true);

    const intake_config: IntakeConfig = {
      assistant_name: assistantName.trim() || undefined,
      welcome_message: welcome.trim() || undefined,
      system_prompt_addition: instructions.trim() || undefined,
      fields_to_collect: DEFAULT_FIELDS,
    };

    // slug is auto-generated by a DB trigger from business_name.
    const { error } = await supabase.from('profiles').insert({
      id: session.user.id,
      email: session.user.email ?? '',
      business_name: businessName.trim(),
      profession: profession.trim(),
      intake_config,
    });

    setSaving(false);
    if (error) {
      setError(error.message);
      return;
    }
    await refreshProfile();
    navigate('/dashboard');
  }

  return (
    <main className="min-h-dvh bg-paper text-ink flex items-center justify-center p-6">
      <form onSubmit={onSubmit} className="rise card w-full max-w-lg p-7 space-y-4">
        <div className="space-y-1 pb-1">
          <p className="mono-label">✦ Step 1 of 1</p>
          <h1 className="font-display text-2xl font-bold tracking-tight">Set up your assistant</h1>
          <p className="text-sm text-ink-soft">
            This shapes the conversation your clients will have.
          </p>
        </div>

        <Field label="Business name">
          <input
            required
            value={businessName}
            onChange={(e) => setBusinessName(e.target.value)}
            placeholder="Cabinet Dupont"
            className="input"
          />
        </Field>

        <Field label="Profession">
          <input
            required
            value={profession}
            onChange={(e) => setProfession(e.target.value)}
            placeholder="Dentist"
            className="input"
          />
        </Field>

        <Field label="Assistant name">
          <input
            value={assistantName}
            onChange={(e) => setAssistantName(e.target.value)}
            placeholder="Alex"
            className="input"
          />
        </Field>

        <Field label="Welcome message">
          <textarea
            value={welcome}
            onChange={(e) => setWelcome(e.target.value)}
            placeholder="Hi! Before your appointment, I'd like to ask a few quick questions."
            rows={2}
            className="input"
          />
        </Field>

        <Field label="What should it collect / how should it behave?">
          <textarea
            value={instructions}
            onChange={(e) => setInstructions(e.target.value)}
            placeholder="Collect the reason for the visit, symptoms, urgency, and relevant history."
            rows={3}
            className="input"
          />
        </Field>

        {error && <p className="text-sm text-red-600">{error}</p>}

        <button type="submit" disabled={saving} className="btn-gold w-full">
          {saving ? 'Saving…' : 'Create my assistant'}
        </button>
      </form>
    </main>
  );
}

function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <label className="block space-y-1">
      <span className="text-sm font-medium text-ink">{label}</span>
      {children}
    </label>
  );
}
